### ISSUE TITLE
`Uncaught TypeError: (0 , _toolkit.createAsyncThunk) is not a function` when upgrading to v2

### ISSUE THREAD

**Issue by dwiyatci** [reduxjs/redux-toolkit#4474]
This should be similar to https://github.com/reduxjs/redux-toolkit/issues/4287, but for us I strongly believe it's related to `exports...default` specified in `package.json` and the way we're building and bundling our project.

It's a corporate project so I cannot share it but I will try to reconstruct what we're facing with a minimum reproducible repo (haven't got a chance to do this today - sorry 🙏🙁). Some packages that (I think) are relevant to this issue:
- `react-scripts@5.0.1` (with `react-app-rewired@2.2.1`)
- `babel@7`
- `webpack@5`

### The issue

For this piece of code:
```js
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

console.log('hi');
console.log({ createAsyncThunk, createSlice }); // { createAsyncThunk: undefined, createSlice: undefined }
```

our app choked when calling any functions from `@reduxjs/toolkit` because they're `undefined`, e.g.: 
```
Uncaught TypeError: (0 , _toolkit.createAsyncThunk) is not a function
```

### Hypothesis

It's probably got something to do with the way we bootstrap our project. In this (big) project, we do building and bundling separately, i.e. we build the JS files first using `@babel/cli` and only then we feed these built files (in a `lib` folder) to `webpack` to be resolved and bundled. Downgrading the package to v1.9.7 makes everything work again so I'm guessing this is because the `exports` hash introduced in v2 is not compatible anymore somehow with how this project is built and bundled.

### Additional info

Things started to work (those functions from RTK become defined) again when I tried to "monkeypatch" this bit in RTK's `package.json` file from:
```json
"exports": {
  ".": {
    "types": "./dist/index.d.ts",
    "import": "./dist/redux-toolkit.modern.mjs",
    "default": "./dist/cjs/index.js"
  }
}
```
to:
```json
"exports": {
  ".": {
    "types": "./dist/index.d.ts",
    "import": "./dist/redux-toolkit.modern.mjs",
    "default": "./dist/redux-toolkit.modern.mjs"
  }
}
```

### Config files
**babel.config.js**
```js
module.exports = function (api) {
  api.cache(true);

  const presets = [
    [
      '@babel/preset-env',
      {
        targets: {
          browsers: [
            'last 2 chrome versions',
            'last 2 firefox versions',
            'last 2 edge versions',
            'last 2 safari versions',
          ],
        },
        useBuiltIns: 'entry',
        corejs: '3.26',
        debug: false,
      },
    ],
    ['@babel/preset-react', { runtime: 'automatic' }],
  ];
  const plugins = [
    [
      '@babel/plugin-transform-runtime',
      {
        absoluteRuntime: false,
        helpers: true,
        regenerator: true,
      },
    ],
    '@babel/plugin-proposal-export-default-from',
    ['@babel/plugin-proposal-pipeline-operator', { proposal: 'hack', topicToken: '^^' }],
    'babel-plugin-lodash',
    'transform-compress-graphql',
  ];

  const babelrcRoots = ['.'];

  return {
    presets,
    plugins,
    babelrcRoots,
  };
};
```

**config-overrides.js** (for react-app-rewired/webpack5)
```js
const webpack = require('webpack');

// override base create-react-app webpack config
module.exports = function override(config) {
  // eslint-disable-next-line no-param-reassign
  config.resolve.fallback = {
    ...config.resolve.fallback,
    'process/browser': require.resolve('process/browser'),
  };

  return config;
};
```

I'd hope that you guys could help with initial analysis of what's really happening here 'cause I'm not really deep into this JS module stuff yet (while I'm trying to prepare the minimum reproducible repo). Thanks a heap! 🙇🏻

**Comment by markerikson** [comment]
That _sounds_ like it's some form of ESM/CJS interop issue, which I know is a broad hand-wavy way to describe it. I would really need to see a repro in order to examine the build output and see what _kind_ of interop issue it is. In general, though, it's some form of mismatch between how the different module types get defined and imported, related to your own project's build setup.

**Comment by dwiyatci** [comment]
Sorry for a bit of delay (life gets in the way - goes without saying 😅). Here's the repo/branch:
https://github.com/dwiyatci/redux-toolkit-login-flow/tree/repro/rtk-issue-4474 (`pnpm start`)

In [this line](https://github.com/dwiyatci/redux-toolkit-login-flow/blob/repro/rtk-issue-4474/src/index.js#L7), I tried to make a resemblance of importing entry point file (that's transpiled by Babel) of one of our packages in our monorepo project.

I can confirm downgrading to v1.9.7 makes it work again in this repro setup, too.

**Comment by dwiyatci** [comment]
@markerikson Any pointer? :)

**Comment by markerikson** [comment]
No, sorry, haven't had any time to look at issues lately.

**Comment by aryaemami59** [comment]
@dwiyatci Thanks for the repro, I looked into it, the issue is related to [this](https://github.com/facebook/create-react-app/issues/11889). This is more of a `react-scripts` issue than an RTK issue. The problem is `react-scripts` doesn't properly resolve `.cjs` extensions, it bundles them as a static file and puts them in `build/static/media` folder. This wasn't an issue prior to RTK 2.0 because `react-scripts` would resolve the `module` field in `package.json` which was `./dist/redux-toolkit.esm.js`, but since in RTK v2.0, the `exports` conditions were added, `react-scripts` resolves the `default` exports condition which is `./dist/cjs/index.js` which directly imports `./dist/cjs/redux-toolkit.development.cjs` which causes the problem due to `react-scripts` not properly bunding `.cjs` extensions. You should be able to solve this issue by modifying your setup (not sure how, not really familiar with `react-app-rewired`), because even if we change all the Redux packages' CJS build artifacts to have a `.js` extension instead of a `.cjs` extension, you'll most likely run into this issue again with some other dependency.

**Comment by markerikson** [comment]
Wait, I'm confused. `react-scripts@5` uses a decently recent Webpack.  Why is it even resolving to the `.cjs` extension in the first place?  It should be finding the ESM artifact.

**Comment by aryaemami59** [comment]
@markerikson I'm not entirely sure tbh, in the provided repro, [this line](https://github.com/dwiyatci/redux-toolkit-login-flow/blob/repro/rtk-issue-4474/src/index.js#L7) imports from `./transpiled/app/store` which kind of confuses me because we're supposed to import from `./app/store` and if we do that, the issue goes away so I'm not sure if that line was added to showcase the issue or if it was added by mistake, @dwiyatci might be able to answer that question.

**Comment by dwiyatci** [comment]
> Thanks for the repro, I looked into it, the issue is related to [this](https://github.com/facebook/create-react-app/issues/11889).

Thanks a lot for this! It was more than enough to get me going and solved the issue. Based on the discussion there, and what you pointed out, [I overrode the webpack config](https://github.com/dwiyatci/redux-toolkit-login-flow/blob/repro/rtk-issue-4474/config-overrides.js#L12) to make `.cjs` extension to be excluded being treated as asset/resource, therefore the module/dependency graph can be followed/resolved correctly again.

```js
config.module.rules
    .find((rule) => rule.oneOf)
    ?.oneOf.find(({ type }) => type === 'asset/resource')
    ?.exclude.push(/\.cjs$/);
``` 


> [this line](https://github.com/dwiyatci/redux-toolkit-login-flow/blob/repro/rtk-issue-4474/src/index.js#L7) imports from `./transpiled/app/store` which kind of confuses me because we're supposed to import from `./app/store`

Yep, as I wrote above, that line is for showcasing the issue, to create a minimum repro example.
 

> even if we change all the Redux packages' CJS build artifacts to have a `.js` extension instead of a `.cjs` extension, you'll most likely run into this issue again with some other dependency.

I can only tell that as the dependencies upgrade in our project is going so far, `@reduxjs/toolkit` is the only dependency that breaks because of this `.cjs` issue. 🙃 But yeah, I'm just gonna leave it to you guys to consider this case as closed then.

Thanks, again, very much, for the support! ᠄)

**Comment by codecell** [comment]
if you're encountering this error on an expo react-native project, 
deleting the custom metro.config file solved this issue for me. My expo v is 51.0. ...

**Comment by hookFang** [comment]
> if you're encountering this error on an expo react-native project, deleting the custom metro.config file solved this issue for me. My expo v is 51.0. ... As stated earlier, this has to do the compilations of cjs assets, e.g const { getDefaultConfig } = require('expo/metro-config'); const defaultConfig = getDefaultConfig(__dirname); defaultConfig.resolver.assetExts.push('cjs')
> 
> So I removed the file entirely and let expo resolve the conflicts under the hood.

Thank you so much this saved my day, I was stuck on this for a while

**Comment by lavor** [comment]
I had also issue with Expo 51. The issue was indeed in my metro.config.js, but it is no necessary to remove whole config.

**Problem is when you additionally add 'cjs' in `resolver.assetExts`, just remove it and it will fix this issue.**

'cjs' should be in resolver.sourceExts, but it is already there (in Expo 51) if you are extending `getDefaultConfig` from 'expo/metro-config'.
