### ISSUE TITLE
Default `EnhancedStore.dispatch` unusable in TS in 1.8.0?

### ISSUE THREAD

**Issue by joshkel** [reduxjs/redux-toolkit#2092]
1.8.0's changes to middleware dispatch types apparently mean that the default `EnhancedStore.dispatch` is typed as `never` in TypeScript.

```ts
import { CombinedState, configureStore, EnhancedStore } from '@reduxjs/toolkit';

let store: EnhancedStore<CombinedState<{ name: string }>> | undefined;
store = configureStore({ reducer: (state) => state || { name: 'Test'} });
store.dispatch({});
```

In RTK 1.8.0, this results in the following TypeScript error:

```
This expression is not callable.
  Type 'never' has no call signatures. ts(2349)
```

In RTK 1.7.2, it compiles without errors.

I can work around this by specifying my own middleware type argument to `EnhancedStore` or by inferring the type with `typeof`, but that feels much more awkward.

Thank you.

**Comment by markerikson** [comment]
You really shouldn't be using the `EnhancedStore` type directly in the first place. We've always specifically recommended inferring the type:

https://redux-toolkit.js.org/tutorials/typescript#define-root-state-and-dispatch-types

Really, many of our types are not intended for actual use in application code due to their complexity.

**Comment by phryneas** [comment]
Which in short means, this really should just be
```ts
import { configureStore } from '@reduxjs/toolkit';

const store = configureStore({ reducer: (state: { name: string } | undefined) => state || { name: 'Test'} });
store.dispatch({});
```

no type annotation.

**Comment by joshkel** [comment]
Thanks for the quick replies.

I'm having trouble figuring out how to get type inference to work for some of my test code. For example:

```ts
describe('JestExample', () => {
  let store: EnhancedStore; // What do I do here?
  beforeEach(() => {
    store = configureStore(...);
  });
});
```

I think I could pull this specific `configureStore` call into a function and then do a `ReturnType<typeof myConfigureStore>`, although some of my tests are too complex to easily do this.

Or, based off of the [example of testing components](https://redux.js.org/usage/writing-tests#components) in the RTK docs:

```ts
function render<T>(
  ui: React.ReactElement,
  { preloadedState, store, ...renderOptions }:
    { preloadedState?: T, store: EnhancedStore<T> } & RenderOptions
) {
  function Wrapper({ children }: { children: React.ReactNode }) {
    return <Provider store={store}>{children}</Provider>
  }
  return rtlRender(ui, { wrapper: Wrapper, ...renderOptions })
}
```

If I'm understanding correctly, I could let the type of `store` be inferred by providing a default value for `store` that calls `configureStore` (like the RTK docs' example). However, since nearly all of my React components' tests depend on this `render` function, declaring a complete default `store` value would mean that every React component depends on every reducer and every data structure and piece of business logic used by every reducer. By using generics (the `<T>` in this example), my render function could accept whatever store it was given, allowing individual tests to manage their own dependencies, so that touching one dependency doesn't result in Jest's watch mode rerunning every test.

Any suggestions? I appreciate the information on intended usage; if I'm simply outside of the intended usage of RTK and am using `EnhancedStore` at my own risk, I'm okay with that.

**Comment by markerikson** [comment]
FWIW, if for some reason you _do_ need to get the correct type of the store with all types _before_ you create it, you can work around it like this (and yes, I've done this for that exact testing scenario):

```ts
const rootReducer = combineReducers({
  posts: postReducer
})

type RootState = ReturnType<typeof rootReducer>

// Use this somewhere to actually create the store
function initStore(preloadedState?: Partial<RootState>) {
  return configureStore({
    reducer: rootReducer,
    preloadedState,
    // any other config settings here
  })
}

type AppStore = ReturnType<typeof initStore>;
type AppDispatch = AppStore['dispatch']
```

Alternately, do an actual `let store = configureStore()` call once in the setup, then still re-create it in `beforeEach()`.

Per the specific question of "my component tests depend on a full store"... yes, that's probably how you should be writing the tests in the first place.  I suppose it's possible to make the `render` function more generic somehow, but I haven't tried.

**Comment by joshkel** [comment]
I found out that Redux's `Store` type is simple to use and avoids these problems (as long as I don't care RTK's enhancements to `dispatch` - and, for this particular test code, I don't).

I'll keep these alternatives in mind for future work. I really appreciate the quick replies and thorough information.

**Comment by markerikson** [comment]
Yeah, if all you need to do is create a placeholder variable for a store in tests, `Store` is reasonable here.

**Comment by nuarhu** [comment]
There is still an issue when upgrading from 1.7.2 to 1.8.0 even with a store setup as explained in the documentation.

The following code and any calls to `dispatch` initialized via `const dispatch = useDispatch<AppDispatch>()` run fine through the compiler (TS 4.5.5) with version 1.7.2 but don't with version 1.8.0:


```typescript
import { useDispatch } from 'react-redux'
import { configureStore, ConfigureStoreOptions } from '@reduxjs/toolkit'
import { setupListeners } from '@reduxjs/toolkit/query'

import { baseApi } from './slices/base'
import { contactApi } from './slices/contact'
import { feedbackSlice } from './slices/feedback'

const options: ConfigureStoreOptions = {
  reducer: {
    [baseApi.reducerPath]: baseApi.reducer,
    [contactApi.reducerPath]: contactApi.reducer,
    [feedbackSlice.name]: feedbackSlice.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(
      baseApi.middleware,
      contactApi.middleware,
    ),
}

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
// eslint-disable-next-line no-undef
if (ESBUILD_DEBUG) { // replaced during build
  options.devTools = true
}

export const store = configureStore(options)

setupListeners(store.dispatch)

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>
// Inferred type depends on reducers
export type AppDispatch = typeof store.dispatch
```

Example for a compiler error with 1.8.0:

> src/components/AuthLoader.tsx:21:5 - error TS2349: This expression is not callable.
>   Type 'never' has no call signatures.
> 
> 21     dispatch(setLoading(isLoading))

**Comment by nuarhu** [comment]
@markerikson here is the sandbox, and more specifically the file where that error is visible: https://codesandbox.io/s/rtk-1-8-0-issue-2092-cz8x1l?file=/src/components/Feedback.tsx

The compiler of the sandbox itself does not log it though. I'm a bit confused how to get it to output this (this is my first sandbox of this kind).

**Comment by markerikson** [comment]
Okay, the issue here is the use of a separate `ConfigureStoreOptions`.  You've erased any actual types that could be inferred.

Please don't write that separately.  If you do everything inline in `configureStore`, the types are correct:

```ts
export const store = configureStore({
  reducer: {
    [feedbackSlice.name]: feedbackSlice.reducer
  },
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat()
});
```

![image](https://user-images.githubusercontent.com/1128784/157085663-804af8ec-23bc-4d36-b562-a452dc9e7fef.png)

**Comment by nuarhu** [comment]
@markerikson thanks a LOT for your quick reactions.

I have solved it by using `any` instead of explicit types like this:

```typescript
const options: any = {
  reducer: {
    [baseApi.reducerPath]: baseApi.reducer,
    [contactApi.reducerPath]: contactApi.reducer,
    [feedbackSlice.name]: feedbackSlice.reducer,
  },
  middleware: (getDefaultMiddleware: any) =>
    getDefaultMiddleware().concat(
      baseApi.middleware,
      contactApi.middleware,
    ),
}
```

It took me a while to get the devtools thing with my esbuild setup to work so I tried it like this first.

**Comment by markerikson** [comment]
**Please don't do that either!**

You're going to wipe out any of the types here.  **That is a very _bad_ idea!**

What I'm suggesting is something like:

```ts
let devTools: boolean | undefined = undefined;

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
// eslint-disable-next-line no-undef
if (ESBUILD_DEBUG) { // replaced during build
  devTools = true
}

const store = configureStore({
  reducer: {
    [baseApi.reducerPath]: baseApi.reducer,
    [contactApi.reducerPath]: contactApi.reducer,
    [feedbackSlice.name]: feedbackSlice.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(
      baseApi.middleware,
      contactApi.middleware,
    ),
})
```

**Comment by phryneas** [comment]
Generally, when using RTK you should never declare an explicit type for a variable. That is erasing all type information until there is only the info "Yeah, this has the shape of a configuration. Maybe there are reducers in there. Maybe middleware." is left.

**Comment by nuarhu** [comment]
@markerikson thank you for your feedback

when I change it to this:

```typescript
import { configureStore } from '@reduxjs/toolkit'
import { setupListeners } from '@reduxjs/toolkit/query'

import { baseApi } from './slices/base'
import { contactApi } from './slices/contact'
import { feedbackSlice } from './slices/feedback'
import { assessmentApi } from './slices/assessment'

let devTools: boolean | undefined = undefined;

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
// eslint-disable-next-line no-undef
if (ESBUILD_DEBUG) { // replaced during build
  devTools = true
}

// @ts-ignore   <<< does not matter if this is in or not
export const store = configureStore({
  devTools: devTools,
  reducer: {
    [baseApi.reducerPath]: baseApi.reducer,
    [contactApi.reducerPath]: contactApi.reducer,
    [assessmentApi.reducerPath]: assessmentApi.reducer,
    [feedbackSlice.name]: feedbackSlice.reducer,
  },
  middleware: (getDefaultMiddleware: any) =>
    getDefaultMiddleware().concat(
      baseApi.middleware,
      contactApi.middleware,
      assessmentApi.middleware,
    ),
})
```

the following error is reported:

> src/redux/store.ts:18:14 - error TS4023: Exported variable 'store' has or is using name 'UpdateAssessmentArgs' from external module "/Users/cackermann/devel/git/cody_care/frontend/src/redux/slices/assessment" but cannot be named.
> 
> 18 export const store = configureStore({

It is still reported even if I add `@ts-ignore`.

**Comment by nuarhu** [comment]
Sorry for the spam, everyone.

Instead of deleting or editing my previous post I still add this answer as it might save other people some time.

My problem was due to my specific code. In one of the rtk apis (the ones created via `createApi`) I was using a local, not exported TS interface. Exporting that interface solved the above TS error. Now, it all works without explicitly typing it.

Thanks again @markerikson for your help.

**Comment by Vita-Meow** [comment]
Thanks for the information, it is really helpful;
But for me,  it really hard to say this type of definition change of Dispatch is compatible with v 17.  Because if the same input didn't make the same output or at least with no impact.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/51940749/161101491-d4375de5-a695-4243-93b3-fe5dc37a7109.png">

**Comment by markerikson** [comment]
@Vita-Meow I'm afraid I really don't understand what you're trying to say there.  Can you clarify?

I'm also not sure what you mean by "compatible with v17".

**Comment by obriankevin11** [comment]
I'm facing the same issue. How is it possible to pass preloadedstate to the store with this config?

**Comment by phryneas** [comment]
@obriankevin11 if you have the exact same issue, please see the message above yours: we don't understand that issue and need clarification.

If you have another issue, please open a new issue and provide enough context.
