### ISSUE TITLE
TypeScript Error in RTK Query 2.4.0 Internal Types

### ISSUE THREAD

**Issue by iustin-nita** [reduxjs/redux-toolkit#4807]
### Description
After upgrading from RTK Query 2.3.0 to 2.4.0 (or 2.5.0), I'm getting a TypeScript error in the internal RTK Query code, specifically in `endpointDefinitions.ts`. This occurs even though I'm not using any tags in my API definitions.

### Reproduction
Here's a minimal setup that triggers the error:
``` 
// api.ts
import { createApi } from '@reduxjs/toolkit/query/react';
const baseQuery = async (args: any) => ({ data: args });
export const api = createApi({
reducerPath: 'api',
baseQuery,
endpoints: () => ({}),
});
```

### Error Message

```
Successfully compiled 7120 files with Babel (18308ms).
Successfully compiled 7120 files with Babel (21611ms).
../../node_modules/@reduxjs/toolkit/src/query/endpointDefinitions.ts:787:28 - error TS2345: Argument of type '(description: TagDescription<string>) => FullTagDescription<string>' is not assignable to parameter of type '(value: TagDescription<string> | null | undefined, index: number, array: readonly (TagDescription<string> | null | undefined)[]) => FullTagDescription<string>'.
  Types of parameters 'description' and 'value' are incompatible.
    Type 'TagDescription<string> | null | undefined' is not assignable to type 'TagDescription<string>'.
      Type 'undefined' is not assignable to type 'TagDescription<string>'.

787     return description.map(expandTagDescription).map(assertTagTypes)
                               ~~~~~~~~~~~~~~~~~~~~


Found 1 error in ../../node_modules/@reduxjs/toolkit/src/query/endpointDefinitions.ts:787
```

### Environment
- RTK version: 2.4.0/2.5.0
- TypeScript version: 5.7.2
- Node version: v22.11.0
- OS: macOS 24.3.0

### Additional Context
- This worked fine in RTK Query 2.3.0
- The error occurs in RTK's internal code when handling tag descriptions
- The error persists even when:
  - Not using any tags in the API definition
  - Using empty tag types (`tagTypes: []`)

### Attempted Solution
Using explicit tag types
```
export const api = createApi({
  reducerPath: 'api',
  baseQuery,
  tagTypes: [] as const,
  endpoints: () => ({}),
});
```

### Expected Behavior
The TypeScript compilation should succeed when not using any tags in the API definition.

### Actual Behavior
TypeScript compilation fails due to an internal type error in RTK Query's tag handling code.

**Comment by EskiMojo14** [comment]
your TS shouldn't be typechecking our source code at all - do you have any imports from `@reduxjs/toolkit/src`?

**Comment by markerikson** [comment]
@iustin-nita oh dear. Please don't :( _Never_ import from `/src` :(  As Ben said, all those should be imported from `@reduxjs/toolkit`, `@reduxjs/toolkit/query`, or `@reduxjs/toolkit/query/react` instead.
