### ISSUE TITLE
Type errors in call to configureStore after updating to RTK v1.6.0 / Redux v4.1.0

### ISSUE THREAD

**Issue by mq2thez** [reduxjs/redux-toolkit#1296]
Hey folks,

After updating to v1.6.0, I started getting the following errors in the helper function which calls `configureStore`:

```
htdocs/assets/js/util/react/createStore.ts:49:9 - error TS2322: Type 'State' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>> | undefined'.
  Type 'State' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>>'.

49         preloadedState: state,
           ~~~~~~~~~~~~~~

  node_modules/@reduxjs/toolkit/dist/configureStore.d.ts:41:5
    41     preloadedState?: PreloadedState<CombinedState<NoInfer<S>>>;
           ~~~~~~~~~~~~~~
    The expected type comes from property 'preloadedState' which is declared here on type 'ConfigureStoreOptions<State, AnyAction, [ThunkMiddleware<State, AnyAction, null> | ThunkMiddleware<State, AnyAction, undefined>]>'

htdocs/assets/js/util/react/createStore.ts:56:9 - error TS2322: Type '(getDefaultMiddleware: CurriedGetDefaultMiddleware<State>) => MiddlewareArray<Middleware<{}, any, Dispatch<AnyAction>> | ThunkMiddleware<...> | ThunkMiddleware<...> | Middleware<...>>' is not assignable to type '[ThunkMiddleware<State, AnyAction, null> | ThunkMiddleware<State, AnyAction, undefined>] | ((getDefaultMiddleware: CurriedGetDefaultMiddleware<...>) => [...]) | undefined'.
  Type '(getDefaultMiddleware: CurriedGetDefaultMiddleware<State>) => MiddlewareArray<Middleware<{}, any, Dispatch<AnyAction>> | ThunkMiddleware<...> | ThunkMiddleware<...> | Middleware<...>>' is not assignable to type '(getDefaultMiddleware: CurriedGetDefaultMiddleware<State>) => [ThunkMiddleware<State, AnyAction, null> | ThunkMiddleware<...>]'.
    Property '0' is missing in type 'MiddlewareArray<Middleware<{}, any, Dispatch<AnyAction>> | ThunkMiddleware<State, AnyAction, null> | ThunkMiddleware<State, AnyAction, undefined> | Middleware<...>>' but required in type '[ThunkMiddleware<State, AnyAction, null> | ThunkMiddleware<State, AnyAction, undefined>]'.

56         middleware: (getDefaultMiddleware) =>
           ~~~~~~~~~~

  node_modules/@reduxjs/toolkit/dist/configureStore.d.ts:26:5
    26     middleware?: ((getDefaultMiddleware: CurriedGetDefaultMiddleware<S>) => M) | M;
           ~~~~~~~~~~
    The expected type comes from property 'middleware' which is declared here on type 'ConfigureStoreOptions<State, AnyAction, [ThunkMiddleware<State, AnyAction, null> | ThunkMiddleware<State, AnyAction, undefined>]>'
```

The code snippet itself (with a few things removed for readability) is:
```ts
import type { Reducer } from "redux";
import { configureStore } from "@reduxjs/toolkit";

export default function createStore<State>(reducer: Reducer<State>, state: State) {
    return configureStore({
        reducer,
        preloadedState: state,
        middleware: (getDefaultMiddleware) =>
            getDefaultMiddleware({
                serializableCheck: false,
                immutableCheck: false,
            }),
    });
}
```

Does anyone have any insight into what might have caused this change?

The weirdest part is that VSCode doesn't seem to think it's an issue -- it only occurs when I run our typechecker from the command line. I was worried that maybe it was a `node_modules` issue, but blowing away `node_modules` and reinstalling didn't have any impact.

**Comment by msutkowski** [comment]
I believe this should be typed like the following, but Lenz might chime in and correct me:

```ts
export default function createStore<R extends Reducer, State>(reducer: R, state: ConfigureStoreOptions<State>['preloadedState']) {
    return configureStore({
        reducer,
        preloadedState: state,
        middleware: (getDefaultMiddleware) =>
            getDefaultMiddleware({
                serializableCheck: false,
                immutableCheck: false,
            }),
    });
}
```

**Comment by mq2thez** [comment]
Hey @msutkowski, thanks for the response! Unfortunately, that doesn't seem to work for me. Using `PreloadedState<RootState>` there causes me to get the following type error:

```
Type 'PreloadedState<State>' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>> | undefined'.
  Type '(State extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : never) | { [K in keyof State]: State[K] extends string | ... 2 more ... | symbol ? State[K] : PreloadedState<...>; }' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>> | undefined'.
    Type 'State extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : never' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>> | undefined'.
      Type '{ [K in keyof State]?: (State[K] extends object ? PreloadedState<State[K]> : State[K]) | undefined; }' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>>'.
        Type 'State extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : never' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>>'.
          Type 'PreloadedState<State>' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>>'.
            Type '(State extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : never) | { [K in keyof State]: State[K] extends string | ... 2 more ... | symbol ? State[K] : PreloadedState<...>; }' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>>'.
              Type 'State extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : never' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>>'.
                Type '{ [K in keyof State]?: (State[K] extends object ? PreloadedState<State[K]> : State[K]) | undefined; }' is not assignable to type 'PreloadedState<CombinedState<NoInfer<State>>>'.
                  Type '{}' is not assignable to type 'CombinedState<NoInfer<State>> extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : never'.
                    Type '{ [K in keyof State]: State[K] extends string | number | boolean | symbol ? State[K] : PreloadedState<State[K]>; }' is not assignable to type '{ [K in keyof CombinedState<NoInfer<State>>]: CombinedState<NoInfer<State>>[K] extends string | number | boolean | symbol ? CombinedState<NoInfer<...>>[K] : PreloadedState<...>; }'.
                      Type 'unique symbol | keyof NoInfer<State>' is not assignable to type 'keyof State'.
                        Type 'typeof $CombinedState' is not assignable to type 'keyof State'.
```

**Comment by mq2thez** [comment]
While I'm never a fan of having to use `as`, it seems like trying to handle our codebase's mix of Immutable/non-Immutable ends up being a headache, so we're just going to wind up with `as` and go from there:

```
export default function createStore<State>(reducer: Reducer<State>, state: State) {
    const preloadedState = state as ConfigureStoreOptions<State>["preloadedState"];
    return configureStore({
        reducer,
        preloadedState,
        ...
```
