### PR TITLE
fix types for TS 4.5

### LINKED ISSUE #1833: [@reduxjs/toolkit: 1.6.2 → 1.7.0] TS2344: Type 'Definitions[EndpointName]' does not satisfy the constraint 'QueryDefinition<any, any, any, any, string>'.
I ran the `tsc` command immediately after updating reduxjs/toolkit from 1.6.2 to 1.7.0, and encountered this error.  

There is no way I can read this and understand it, can anyone tell me the cause or give me a clue?

```csharp
Error: node_modules/@reduxjs/toolkit/dist/query/core/module.d.ts(100,183): error TS2344: Type 'Definitions[EndpointName]' does not satisfy the constraint 'MutationDefinition<any, any, any, any, string>'.
  Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
    Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
      Type 'Definitions[keyof Definitions]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
        Type 'Definitions[string] | Definitions[number] | Definitions[symbol]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
          Type 'Definitions[string]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
            Type 'EndpointDefinition<any, any, any, any, string>' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
              Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
                Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                  Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'MutationExtraOptions<any, any, any, any, string>'.
                    Types of property 'type' are incompatible.
                      Type 'DefinitionType.query' is not assignable to type 'DefinitionType.mutation'.
                        Type 'Definitions[string]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                          Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                            Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                              Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                Type 'Definitions[EndpointName]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                  Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                    Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                      Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                        Type 'Definitions[string] | Definitions[number] | Definitions[symbol]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                          Type 'Definitions[string]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                            Type 'EndpointDefinition<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                              Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                                Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                  Type 'Definitions[string]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                    Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                      Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                        Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                          Type 'Definitions[EndpointName]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                            Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                              Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                                Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
```

[](https://st.elmah.io)

### envirionment
TypeScirpt v4.5.4
node: 16.9
github actions container

# Reproduction
https://github.com/laststance/react-re-render-rules/runs/4494596354?check_suite_focus=true

### PR DESCRIPTION
**Pull request by phryneas**
first half of patch: trigger the error in CI so we catch things like this in the future
second half: fix types

Fixes #1833 and #1829

### CODE REVIEW

File: .yarn/patches/console-testing-library__npm_0.3.1.patch [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ 
+ export function createConsole(options?: Options): TestingConsole;
+ 
+ export function mockConsole(
+   testingConsole: TestingConsole,
+-  targetConsoleParent?: {} = global,
++  targetConsoleParent?: typeof globalThis,
+   targetConsoleKey?: string
+ ): () => void;
+
```
Comment (phryneas) [inline .yarn/patches/console-testing-library__npm_0.3.1.patch:26]: I've also created a PR for this: https://github.com/kevin940726/console-testing-library/pull/25 - but until that is released I'm just adding it as a yarn patch here.

**Comment by phryneas** [comment]
@markerikson could you please take a look at this and maybe release a 1.7.1?

**Comment by markerikson** [comment]
Yeah, busy with work atm but I can put out 1.7.1 tonight.

**Comment by ryota-murakami** [comment]
@phryneas why not just update to TypeScript v4.5.4 that current latest?

**Comment by phryneas** [comment]
@ryota-murakami TypeScript is way more forward-compatible than backward-compatible. So writing new code that should run in 3.9 - 4.5 is much easier when writing it in an old version of TS than a new version of TS. 
Both directions break from time to time, but developing in a new version breaks more often than developing in an old version. 

That said, there are some 4.1+ features we definitely want to use, so somehow TS version was set to 4.2 - and it will probably stay there until we drop 4.2 support.

**Comment by ryota-murakami** [comment]
@phryneas I see, that hard work for support wide range TypeScript version.  
Because TypeScript minor number version up include some new feature and breaking change more than other semver numbering npm.
And there is no Long Term Support version, so not clear what version should support aming.

Type Error tend to occuring just a very slightly difference, I hope coming more confotable evronment for library development with TypeScript.
