### ISSUE TITLE
@reduxjs/rtk-codemods ts-node mismatch error

### ISSUE THREAD

**Issue by andreaHG** [reduxjs/redux-toolkit#3961]
I encountered a TypeScript error when running the `@reduxjs/rtk-codemods` tool. The command executed was:

```bash
npx @reduxjs/rtk-codemods createReducerBuilder ./src
```

**Error Message**:

```zsh
/node_modules/@reduxjs/rtk-codemods/node_modules/typescript/lib/typescript.js:43500

ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");

Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
```

**Temporary Solution**:
In an attempt to debug this issue, I installed `rtk-codemods` package locally and made the following changes:
1. Updated the `ts-node` version to the latest (10.9.1).
2. Temporarily commented out the `ast-types` package due to a subsequent error (`Cannot find module 'ast-types/gen/kinds' or its corresponding type declarations.`).

After these modifications, `rtk-codemods` ran as expected. Any guidance on resolving this issue without these temporary fixes would be great but leaving incase it helps. 

**Note**: I was working with `@reduxjs/rtk-codemods` **v0.0.3** but it looks like the latest commits remove ts-node so maybe this will be fixed in an upcoming release?

**Comment by andrei10k** [comment]
i have the same error. i don't even have typescript in my project

**Comment by aryaemami59** [comment]
I believe this was fixed in v0.1.2.

**Comment by EskiMojo14** [comment]
closing as we've changed the codemod setup significantly - please let us know if this is still an issue!
