### ISSUE TITLE
Typescript 4.7.3 incorrect typing

### ISSUE THREAD

**Issue by rus-yurchenko** [reduxjs/redux-toolkit#2391]
After migrating to Typescript 4.7.3 from 4.3.5 I'm getting the following compilation error:
```
ERROR in node_modules/@reduxjs/toolkit/src/createAsyncThunk.ts:533:11
Type '{ aborted: false; addEventListener(): void; dispatchEvent(): false; onabort(this: AbortSignal): void; removeEventListener(): void; }' is missing the following properties from type 'AbortSignal': reason, throwIfAborted
```

Note that #2156 doesn't help since I only use import from `@reduxjs/toolkit`.

Looking forward to hearing from you. Thanks.
