### ISSUE TITLE
Get result from async dispatch(ThunkAction)

### ISSUE THREAD

**Issue by brightsider** [reduxjs/redux-toolkit#3401]
Hello. I've got the issue after updating from 1.9.3 to 1.9.5.

I have this code:
```
export interface ContactsBatchResult {
  successful?: string;
  failed?: string;
}

export const sendSMS =
  (
    props: SMSBatchPayload
  ): ThunkAction<Promise<ContactsBatchResult>, RootState, unknown, AnyAction> =>
  async (dispatch, getState): Promise<ContactsBatchResult> => {
...
  };
  
const { successful, failed } = await dispatch(
      sendSMS({
...
      })
    );
```

Issue:
```
error TS2339: Property 'successful' does not exist on type 'AsyncThunkAction<ContactsBatchResult, SMSBatchPayload, { state: EmptyObject & { auth: AuthState; call: CallData; loader: { ...; }; ... 92 more ...; hospitalsReferralsApi: CombinedState<...>; }; ... 6 more ...; rejectedMeta?: unknown; }>'.

const { successful, failed } = await dispatch(
```

I did try to redo to use createAsyncThunk and it doesn't help.
I googled a lot and can't find a resolution.

**Comment by phryneas** [comment]
You likely have a defunct `Dispatch` type. Did you change your store setup/how does your store setup look?

**Comment by brightsider** [comment]
Yes.
I use this:

```
export const store = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) => [
    ...getDefaultMiddleware(),
...
  ],
});

export type AppDispatch = typeof store.dispatch;

export const useAppDispatch = () => useDispatch<AppDispatch>();
```

**Comment by brightsider** [comment]
When I changed to native useDispatch I get this:

```
'await' has no effect on the type of this expression.

Argument of type 'ThunkAction<Promise<ContactsBatchResult>, EmptyObject & { auth: AuthState; call: CallData; loader: { isLoading: boolean; }; ... 92 more ...; hospitalsReferralsApi: CombinedState<...>; }, unknown, AnyAction>' is not assignable to parameter of type 'AnyAction'.

       sendSMS({
          ~~~~~~~~~
         phones: [phone],
    ~~~~~~~~~~~~~~~~~~~~~~~~
... 
         }),
    ~~~~~~~~~~~
       })
    ~~~~~~~~
```

**Comment by markerikson** [comment]
@brightsider : yeah, there's two problems there.

First, when you spread `[...getDefaultMiddleware()]` like that, TS loses the specific type information.  So, it no longer knows that the thunk middleware is added.

Second, **you _don't need to call `getDefaultMiddleware` at all - it's _already_ called by `configureStore`!**

That can be changed to just:

```ts
export const store = configureStore({
  reducer: rootReducer
})
```

and it will work right.

Out of curiosity, what led you to call `getDefaultMiddleware` with no further customization and an array spread like that?

**Comment by phryneas** [comment]
I think Mark missed the other `...` that should probably denote more middleware - but yes, you should never use the spread operator here. It removes the TypeScript type of your individual middleware and mashes them down to "an array of some middleware".

Please use the `getDefaultMiddleware().concat` method instead as we show it in our docs. Once your middleware types are right, your `Dispatch` type will gain the additional overloads of your middlewares (you are missing the thunk overload) and your code above will not error.

**Comment by phryneas** [comment]
Please show the full code you have now and don't omit some additional middleware you add with `...`

**Comment by brightsider** [comment]
Here is example: https://codesandbox.io/s/toolkit-example-3ou0gz?file=/src/App.tsx

When you change "@reduxjs/toolkit": "1.9.5", to "@reduxjs/toolkit": "1.9.3", error will gone

**Comment by phryneas** [comment]
A reducer should never return `undefined` - after fixing that, your type error goes away:

```diff
const rootReducer = (state: any, action: any) => {
+  if (action.type === "logout") return undefined;
-  if (action.type === "logout") return appReducer(undefined, action);
  return appReducer(state, action);
};
```

**Comment by EskiMojo14** [comment]
the error is a little unintuitive, but the root issue is that your rootReducer is returning `undefined`, which should **never** happen.

Instead, call your appReducer *with* undefined to get its initial state.

```ts
const rootReducer: typeof appReducer = (state, action) => {
  if (action.type === "logout") return appReducer(undefined, action);
  return appReducer(state, action);
};
```

**Comment by brightsider** [comment]
thanks you, guys! its help 🫡
