### ISSUE TITLE
typescript errors after 2.2.6 to 2.2.7 update

### ISSUE THREAD

**Issue by okhomenko** [reduxjs/redux-toolkit#4537]
After updating from 2.2.6 to 2.2.7 getting a blanket of the errors. Can't figure out what is wrong

tsc version `5.5.4`

```bash
➜  webpack git:(webpack/reduxjs/toolkit-2.2.7) ✗ ./node_modules/.bin/tsc --noEmit --skipLibCheck
node_modules/@reduxjs/toolkit/src/query/core/buildInitiate.ts:230:9 - error TS2322: Type 'EndpointDefinition<any, any, any, any, string> | undefined' is not assignable to type 'EndpointDefinition<any, any, any, any>'.
  Type 'undefined' is not assignable to type 'EndpointDefinition<any, any, any, any>'.

230         endpointDefinition,
            ~~~~~~~~~~~~~~~~~~

  node_modules/@reduxjs/toolkit/src/query/defaultSerializeQueryArgs.ts:50:3
    50   endpointDefinition: EndpointDefinition<any, any, any, any>
         ~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'endpointDefinition' which is declared here on type '{ queryArgs: any; endpointDefinition: EndpointDefinition<any, any, any, any>; endpointName: string; }'

node_modules/@reduxjs/toolkit/src/query/core/buildInitiate.ts:322:11 - error TS2352: Conversion of type 'undefined' to type 'ApiEndpointQuery<any, any>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

322           api.endpoints[endpointName] as ApiEndpointQuery<any, any>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/batchActions.ts:109:7 - error TS2322: Type 'unknown' is not assignable to type 'SubscriptionState'.

109       previousSubscriptions = JSON.parse(
          ~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/batchActions.ts:145:17 - error TS2322: Type 'unknown' is not assignable to type 'SubscriptionState'.

145           const newSubscriptions: SubscriptionState = JSON.parse(
                    ~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheCollection.ts:75:9 - error TS18048: 'state' is possibly 'undefined'.

75         state.queries[queryCacheKey]?.endpointName,
           ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheCollection.ts:77:9 - error TS18048: 'state' is possibly 'undefined'.

77         state.config,
           ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheCollection.ts:99:11 - error TS18048: 'state' is possibly 'undefined'.

99           state.config,
             ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheLifecycle.ts:194:24 - error TS2532: Object is possibly 'undefined'.

194       const oldState = stateBefore[reducerPath].queries[cacheKey]
                           ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheLifecycle.ts:195:21 - error TS2532: Object is possibly 'undefined'.

195       const state = mwApi.getState()[reducerPath].queries[cacheKey]
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheLifecycle.ts:206:21 - error TS2532: Object is possibly 'undefined'.

206       const state = mwApi.getState()[reducerPath].mutations[cacheKey]
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/invalidationByTags.ts:98:7 - error TS18048: 'state' is possibly 'undefined'.

98       state.config.invalidationBehavior === 'delayed' &&
         ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/invalidationByTags.ts:99:26 - error TS2345: Argument of type 'CombinedState<EndpointDefinitions, string, string> | undefined' is not assignable to parameter of type 'CombinedState<EndpointDefinitions, string, string>'.
  Type 'undefined' is not assignable to type 'CombinedState<EndpointDefinitions, string, string>'.

99       hasPendingRequests(state)
                            ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/invalidationByTags.ts:113:31 - error TS18048: 'state' is possibly 'undefined'.

113         const querySubState = state.queries[queryCacheKey]
                                  ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/polling.ts:57:27 - error TS18048: 'state' is possibly 'undefined'.

57     const querySubState = state.queries[queryCacheKey]
                             ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/polling.ts:80:13 - error TS18048: 'state' is possibly 'undefined'.

80         if (state.config.focused || !skipPollingIfUnfocused) {
               ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/polling.ts:93:27 - error TS18048: 'state' is possibly 'undefined'.

93     const querySubState = state.queries[queryCacheKey]
                             ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/polling.ts:133:13 - error TS2532: Object is possibly 'undefined'.

133       if (!!subscribers[key].pollingInterval) {
                ~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/polling.ts:135:11 - error TS2532: Object is possibly 'undefined'.

135           subscribers[key].pollingInterval!,
              ~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/polling.ts:139:11 - error TS2532: Object is possibly 'undefined'.

139           subscribers[key].skipPollingIfUnfocused || skipPollingIfUnfocused
              ~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/windowEventHandling.ts:34:21 - error TS18048: 'state' is possibly 'undefined'.

34     const queries = state.queries
                       ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/windowEventHandling.ts:51:13 - error TS18048: 'state' is possibly 'undefined'.

51             state.config[type])
               ~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildSelectors.ts:217:24 - error TS18048: 'apiState' is possibly 'undefined'.

217       const provided = apiState.provided[tag.type]
                           ~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildSelectors.ts:236:31 - error TS18048: 'apiState' is possibly 'undefined'.

236         const querySubState = apiState.queries[queryCacheKey]
                                  ~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildSelectors.ts:254:26 - error TS2532: Object is possibly 'undefined'.

254     return Object.values(state[reducerPath].queries as QueryState<any>)
                             ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildSlice.ts:215:19 - error TS2532: Object is possibly 'undefined'.

215                   definitions[meta.arg.endpointName].structuralSharing ?? true
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:237:9 - error TS2322: Type 'EndpointDefinition<any, any, any, any, string> | undefined' is not assignable to type 'EndpointDefinition<any, any, any, any>'.

237         endpointDefinition,
            ~~~~~~~~~~~~~~~~~~

  node_modules/@reduxjs/toolkit/src/query/defaultSerializeQueryArgs.ts:50:3
    50   endpointDefinition: EndpointDefinition<any, any, any, any>
         ~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'endpointDefinition' which is declared here on type '{ queryArgs: any; endpointDefinition: EndpointDefinition<any, any, any, any>; endpointName: string; }'

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:255:9 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

255         endpointDefinition.providesTags,
            ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:390:18 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

390       } else if (endpointDefinition.query) {
                     ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:392:11 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

392           endpointDefinition.query(arg.originalArgs),
              ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:394:11 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

394           endpointDefinition.extraOptions as any,
              ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:397:13 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

397         if (endpointDefinition.transformResponse) {
                ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:398:31 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

398           transformResponse = endpointDefinition.transformResponse
                                  ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:401:24 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

401         result = await endpointDefinition.queryFn(
                           ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:401:24 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

401         result = await endpointDefinition.queryFn(
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:401:24 - error TS18048: 'endpointDefinition.queryFn' is possibly 'undefined'.

401         result = await endpointDefinition.queryFn(
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:404:11 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

404           endpointDefinition.extraOptions as any,
              ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:409:15 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

409               endpointDefinition.extraOptions as any,
                  ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:417:22 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

417         const what = endpointDefinition.query ? '`baseQuery`' : '`queryFn`'
                         ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:466:11 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

466           endpointDefinition.query &&
              ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:467:11 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

467           endpointDefinition.transformErrorResponse
              ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:469:36 - error TS18048: 'endpointDefinition' is possibly 'undefined'.

469           transformErrorResponse = endpointDefinition.transformErrorResponse
                                       ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:559:27 - error TS2345: Argument of type 'EndpointDefinition<any, any, any, any, string> | undefined' is not assignable to parameter of type 'EndpointDefinition<any, any, any, any, string>'.
  Type 'undefined' is not assignable to type 'EndpointDefinition<any, any, any, any, string>'.

559         isQueryDefinition(endpointDefinition) &&
                              ~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:677:5 - error TS2532: Object is possibly 'undefined'.

677     endpointDefinitions[action.meta.arg.endpointName][type],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/module.ts:611:13 - error TS2345: Argument of type 'ApiEndpointQuery<any, Record<string, any>> | ApiEndpointMutation<any, Record<string, any>> | undefined' is not assignable to parameter of type 'object'.
  Type 'undefined' is not assignable to type 'object'.

611             anyApi.endpoints[endpointName],
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/core/module.ts:621:13 - error TS2345: Argument of type 'ApiEndpointQuery<any, Record<string, any>> | ApiEndpointMutation<any, Record<string, any>> | undefined' is not assignable to parameter of type 'object'.
  Type 'undefined' is not assignable to type 'object'.

621             anyApi.endpoints[endpointName],
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/react/buildHooks.ts:686:11 - error TS2322: Type 'EndpointDefinition<any, any, any, any, string> | undefined' is not assignable to type 'EndpointDefinition<any, any, any, any, string>'.
  Type 'undefined' is not assignable to type 'EndpointDefinition<any, any, any, any, string>'.

686           endpointDefinition,
              ~~~~~~~~~~~~~~~~~~

  node_modules/@reduxjs/toolkit/dist/query/index.d.ts:77:5
    77     endpointDefinition: EndpointDefinition<any, any, any, any>;
           ~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'endpointDefinition' which is declared here on type '{ queryArgs: any; endpointDefinition: EndpointDefinition<any, any, any, any, string>; endpointName: string; }'

node_modules/@reduxjs/toolkit/src/query/react/buildHooks.ts:691:11 - error TS2322: Type 'EndpointDefinition<any, any, any, any, string> | undefined' is not assignable to type 'EndpointDefinition<any, any, any, any, string>'.

691           endpointDefinition,
              ~~~~~~~~~~~~~~~~~~

  node_modules/@reduxjs/toolkit/dist/query/index.d.ts:77:5
    77     endpointDefinition: EndpointDefinition<any, any, any, any>;
           ~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'endpointDefinition' which is declared here on type '{ queryArgs: any; endpointDefinition: EndpointDefinition<any, any, any, any, string>; endpointName: string; }'

node_modules/@reduxjs/toolkit/src/query/react/buildHooks.ts:797:9 - error TS2345: Argument of type 'EndpointDefinition<any, any, any, any, string> | undefined' is not assignable to parameter of type 'EndpointDefinition<any, any, any, any>'.
  Type 'undefined' is not assignable to type 'EndpointDefinition<any, any, any, any>'.

797         context.endpointDefinitions[name],
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/react/buildHooks.ts:1001:9 - error TS2345: Argument of type 'EndpointDefinition<any, any, any, any, string> | undefined' is not assignable to parameter of type 'EndpointDefinition<any, any, any, any>'.

1001         context.endpointDefinitions[name],
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/react/module.ts:216:24 - error TS2345: Argument of type 'QueryHooks<any> | MutationHooks<any> | undefined' is not assignable to parameter of type 'object'.
  Type 'undefined' is not assignable to type 'object'.

216             safeAssign(anyApi.endpoints[endpointName], {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/react/module.ts:228:24 - error TS2345: Argument of type 'QueryHooks<any> | MutationHooks<any> | undefined' is not assignable to parameter of type 'object'.
  Type 'undefined' is not assignable to type 'object'.

228             safeAssign(anyApi.endpoints[endpointName], {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/query/utils/capitalize.ts:2:22 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'string | undefined' is not assignable to parameter of type 'string | RegExp'.
      Type 'undefined' is not assignable to type 'string | RegExp'.

2   return str.replace(str[0], str[0].toUpperCase())
                       ~~~~~~

  node_modules/typescript/lib/lib.es5.d.ts:470:5
    470     replace(searchValue: string | RegExp, replacer: (substring: string, ...args: any[]) => string): string;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.

node_modules/@reduxjs/toolkit/src/query/utils/capitalize.ts:2:30 - error TS2532: Object is possibly 'undefined'.

2   return str.replace(str[0], str[0].toUpperCase())
                               ~~~~~~

node_modules/@reduxjs/toolkit/src/utils.ts:33:23 - error TS2802: Type 'Iterable<T>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.

33   for (const entry of iterable) {
                         ~~~~~~~~


Found 54 errors in 15 files.

Errors  Files
     2  node_modules/@reduxjs/toolkit/src/query/core/buildInitiate.ts:230
     2  node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/batchActions.ts:109
     3  node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheCollection.ts:75
     3  node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/cacheLifecycle.ts:194
     3  node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/invalidationByTags.ts:98
     6  node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/polling.ts:57
     2  node_modules/@reduxjs/toolkit/src/query/core/buildMiddleware/windowEventHandling.ts:34
     3  node_modules/@reduxjs/toolkit/src/query/core/buildSelectors.ts:217
     1  node_modules/@reduxjs/toolkit/src/query/core/buildSlice.ts:215
    18  node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:237
     2  node_modules/@reduxjs/toolkit/src/query/core/module.ts:611
     4  node_modules/@reduxjs/toolkit/src/query/react/buildHooks.ts:686
     2  node_modules/@reduxjs/toolkit/src/query/react/module.ts:216
     2  node_modules/@reduxjs/toolkit/src/query/utils/capitalize.ts:2
     1  node_modules/@reduxjs/toolkit/src/utils.ts:33
➜  webpack git:(bbk-admin-api/src/main/webpack/reduxjs/toolkit-2.2.7) ✗ ./node_modules/.bin/tsc --noEmit --skipLibCheck
```

tsconfig
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react",
    "lib": [
      "esnext",
      "dom",
      "dom.iterable"
    ],
    "allowJs": true,
    "checkJs": false,
    "noEmit": true,
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true,
    // "outDir": "./dist/",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "noImplicitAny": true,
    "isolatedModules": true,
    "sourceMap": true,
    "baseUrl": ".",
    "resolveJsonModule": true
  },
  "exclude": [
    "node_modules"
  ]
}

```

**Comment by markerikson** [comment]
It looks like your TS config is trying to typecheck our actual `src` folder under `node_modules`, which you shouldn't be doing. Can you check your settings and make sure it _won't_ try to do that?

**Comment by aryaemami59** [comment]
Yeah I'm trying to reproduce this issue but can't. @okhomenko If you can give a minimal repro I can definitely take a look.

**Comment by EskiMojo14** [comment]
do you have any imports from `@reduxjs/toolkit/src/`?

**Comment by okhomenko** [comment]
I have only exports from query and query/react, no src. Let me put together the repo to reproduce

**Comment by okhomenko** [comment]
@EskiMojo14 You were right, I had to switch to TypedLazyQueryTrigger in 2.2.7 and make an import from `src/`

in 2.2.6 
```ts
import type { LazyQueryTrigger } from '@reduxjs/toolkit/dist/query/react/buildHooks';
import type { QueryDefinition } from '@reduxjs/toolkit/query';

export const useCreatePollingRequest = <
  T extends LazyQueryTrigger<QueryDefinition<any, any, any, any>>,
>(fn: T) => {}
```

to 2.2.7 
```ts
import { TypedLazyQueryTrigger } from '@reduxjs/toolkit/src/query/react';

export const useCreatePollingRequest = <
  T extends TypedLazyQueryTrigger<{ statusURL: string }, any, any>,
>(fn: T) => {}
```

To fix it I can just switch from `src/` to `dist/`.

**Comment by aryaemami59** [comment]
@okhomenko Do not import anything from either the `src` or `dist` folder, if you want to use `TypedLazyQueryTrigger` you can just do this:

```ts
import type { TypedLazyQueryTrigger } from '@reduxjs/toolkit/query/react'
```

**Comment by okhomenko** [comment]
Thanks for the tip @aryaemami59. That's helpful. Wondering why intellij doesn't pick up auto import from `@reduxjs/toolkit/query/react` and suggesting one from the `dist`

<img width="814" alt="Screenshot 2024-07-31 at 9 44 45 AM" src="https://github.com/user-attachments/assets/2b0122b3-a0d8-44b7-84ef-8a6a9c47cef7">

**Comment by aryaemami59** [comment]
@okhomenko Not really sure. It could be because you've previously imported from that path and intellij wrongly assumes that's the path want to import from now.
