### ISSUE TITLE
[@reduxjs/toolkit: 1.6.2 → 1.7.0] TS2344: Type 'Definitions[EndpointName]' does not satisfy the constraint 'QueryDefinition<any, any, any, any, string>'.

### ISSUE THREAD

**Issue by ryota-murakami** [reduxjs/redux-toolkit#1833]
I ran the `tsc` command immediately after updating reduxjs/toolkit from 1.6.2 to 1.7.0, and encountered this error.  

There is no way I can read this and understand it, can anyone tell me the cause or give me a clue?

```csharp
Error: node_modules/@reduxjs/toolkit/dist/query/core/module.d.ts(100,183): error TS2344: Type 'Definitions[EndpointName]' does not satisfy the constraint 'MutationDefinition<any, any, any, any, string>'.
  Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
    Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
      Type 'Definitions[keyof Definitions]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
        Type 'Definitions[string] | Definitions[number] | Definitions[symbol]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
          Type 'Definitions[string]' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
            Type 'EndpointDefinition<any, any, any, any, string>' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
              Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'MutationDefinition<any, any, any, any, string>'.
                Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                  Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'MutationExtraOptions<any, any, any, any, string>'.
                    Types of property 'type' are incompatible.
                      Type 'DefinitionType.query' is not assignable to type 'DefinitionType.mutation'.
                        Type 'Definitions[string]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                          Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                            Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                              Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                Type 'Definitions[EndpointName]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                  Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                    Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                      Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                        Type 'Definitions[string] | Definitions[number] | Definitions[symbol]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                          Type 'Definitions[string]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                            Type 'EndpointDefinition<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                              Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & MutationExtraOptions<any, any, any, any, string>'.
                                                Type 'EndpointDefinitionWithQueryFn<any, any, any> & { [resultType]?: any; [baseQuery]?: any; } & { extraOptions?: unknown; } & QueryExtraOptions<any, any, any, any, string>' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                  Type 'Definitions[string]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                    Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                      Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                        Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                          Type 'Definitions[EndpointName]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                            Type 'Definitions[MutationKeys<Definitions>]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                              Type 'Definitions[Definitions[keyof Definitions] extends MutationDefinition<any, any, any, any, string> ? keyof Definitions : never]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
                                                                Type 'Definitions[keyof Definitions]' is not assignable to type 'EndpointDefinitionWithQuery<any, any, any>'.
```

[![](https://img.shields.io/badge/Formatted%20by-https%3A%2F%2Fst.elmah.io-%230da58e)](https://st.elmah.io)

### envirionment
TypeScirpt v4.5.4
node: 16.9
github actions container

# Reproduction
https://github.com/laststance/react-re-render-rules/runs/4494596354?check_suite_focus=true

**Comment by markerikson** [comment]
Hoooo-ly smoke, that's ugly :)

Also looks like the same error as #1829, I think?

**Comment by phryneas** [comment]
Seems like this is a problem within our sources that TS 4.2 which we use for building doesn't detect - and then somehow it also doesn't trigger in the type tests

**Comment by ryota-murakami** [comment]
@markerikson 
> Hoooo-ly smoke, that's ugly :)

Isn't this a promising candidate for MEME? like  

![smell-bad](https://user-images.githubusercontent.com/5501268/146243316-1b174051-e130-4cb5-8de3-f6424e290dec.jpg)

**Comment by markerikson** [comment]
Should be fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.1 .

**Comment by ryota-murakami** [comment]
@markerikson @phryneas I confirmed this is fixed, thank you for faster fixing! 😄

**Comment by markerikson** [comment]
heh, thank @phryneas for actually fixing it - I just merged and released :)

**Comment by ryota-murakami** [comment]
@markerikson haha, also I'm getting thousand number count of contributions from Github that showing my top page.
https://github.com/ryota-murakami

But approximately 90% are just merging npm automated dependency update PR from [Depfu](https://depfu.com/).

Honestly increasing number and top page become more green glass is bring me satisfaction, but that's can never say 'contributions'. 😅
