### ISSUE TITLE
Investigate `createAsyncThunk` type failures with TS 5.1+

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3758]
Bumped the TS versions to include 5.1 and 5.2, and got this:

https://github.com/reduxjs/redux-toolkit/actions/runs/6367491100/job/17286119923?pr=3757

```
Run yarn tsc --version
Version 5.1.6
Error: src/tests/createAsyncThunk.typetest.ts(294,39): error TS2345: Argument of type 'AsyncThunk<number, number, AsyncThunkConfig>' is not assignable to parameter of type '(arg?: number | undefined) => any'.
  Types of parameters 'arg' and 'arg' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
Error: src/tests/createAsyncThunk.typetest.ts(295,5): error TS2554: Expected 1 arguments, but got 0.
Error: Process completed with exit code 2.
```

**Comment by EskiMojo14** [comment]
not sure why, but this seems to be a Typescript bug. the second API argument makes the difference:
![image](https://github.com/reduxjs/redux-toolkit/assets/18308300/ed7bd83c-ab2d-4cc3-91ea-bdf5f140a0b4)
![image](https://github.com/reduxjs/redux-toolkit/assets/18308300/0d2e1156-a5c7-43d4-bf7a-072f1fe36307)

**Comment by Andarist** [comment]
I bisected the change to [this diff](https://github.com/microsoft/TypeScript/compare/7f292bf2a19aa14ed69a55e646111af9533d8f1c...ba42ad36467506f81a4f77d536354c4cb90c32d9) so it's almost guaranteed that the change is caused by https://github.com/microsoft/TypeScript/pull/52609

**Comment by markerikson** [comment]
Oh lovely :)

Don't think there's a good way for us to conditionally `// @ts-expect-error` for specific TS versions.  Not sure what the best workaround is for the typetest here.

**Comment by Andarist** [comment]
Ye, it might be tricky for u to handle this specific diff in ur test case. The bigger q is if this is a desired change or not? I think that likely it is intended on the TS side of things but i didnt actually analyze ur types to be sure

**Comment by markerikson** [comment]
I don't fully have the behavior here in my head, but it seems like the typetest worked fine as of TS 5.0, and broke with TS 5.1.  So, that makes me assume that this is _not_ a desired change.

**Comment by Andarist** [comment]
The PR in question started to consider some inference sources that were previously ignored. So it is expected that some scenarios could get affected. I’m unsure yet if this particular change is for good or not - i only looked at a playground that manifested the change but there was no error there. The inferred type was just *different*. Could u create a playground that would show the unintended behavior in a more direct way?

**Comment by EskiMojo14** [comment]
here's a [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgZgWQIYgEYQKoDsAmE4CWWEOAPACoA0U5ATgK4TUBiSANgM4QB8UAvFADa9XPiIkAulAgAPYBFwch5CQH4aDaAC4orThABQBovNpwkAY2gB1WkjCQcAQTAEoAbwNRvUOAHs-HQ5gWiIAcwMAXyNZMD9aYF8RC2ACPywoAHc7MGZk1PTSACUIYHpaLGonWjD+KBE8QmIcbgAKC3Y2VEsAax1WpBqdarDqewIdW3tHFwIASn5eErKKhc8fKFpS8oy4fLSM7OmSVoA6c8FBsIkdeGQ0TFEmklIR6kua1WGaiXer7+u3DWXg2Pi2KwyHTYXV6AxqUCQSjeHl8AR0AHJurR0VBInMANwg7zRaIGCzpYJZHKOOpHXL7dKtVrBWhfKAs8ILPi8AAGABJ3CzIgBCHlzIx0xytcUGSUnBpiZoyuU4Vro9FzIA) for what createAsyncThunk tries to do. Basically, when the payload creator's argument is optional (or possibly undefined) we want to mark the argument as optional in the resulting function. The new behaviour breaks our ability to infer that, because an optional parameter no longer infers as possibly undefined.

**Comment by Andarist** [comment]
Oh, ye - this looks wrong. Luckily... I already fixed this in https://github.com/microsoft/TypeScript/pull/55397 . You can see that the nightly TS version doesn't suffer from this: [TS playground](https://www.typescriptlang.org/play?ts=5.3.0-dev.20231001#code/C4TwDgpgBAkgZgWQIYgEYQKoDsAmE4CWWEOAPACoA0U5ATgK4TUBiSANgM4QB8UAvFADa9XPiIkAulAgAPYBFwch5CQH4aDaAC4orThABQBovNpwkAY2gB1WkjCQcAQTAEoAbwNRvUOAHs-HQ5gWiIAcwMAXyNZMD9aYF8RC2ACPywoAHc7MGZk1PTSACUIYHpaLGonWjD+KBE8QmIcbgAKC3Y2VEsAax1WpBqdarDqewIdW3tHFwIASn5eErKKhc8fKFpS8oy4fLSM7OmSVoA6c8FBsIkdeGQ0TFEmklIR6kua1WGaiXer7+u3DWXg2Pi2KwyHTYXV6AxqUCQSjeHl8AR0AHJurR0VBInMANwg7zRaIGCzpYJZHKOOpHXL7dKtVrBWhfKAs8ILPi8AAGABJ3CzIgBCHlzIx0xytcUGSUnBpiZoyuU4Vro9FzIA)

**Comment by markerikson** [comment]
Well, #3761 is my first use of https://github.com/phryneas/ts-version :)
