### ISSUE TITLE
The inferred type of 'X-Slice' cannot be named without a reference to '@reduxjs/toolkit/node_modules/immer/dist/internal'. This is likely not portable. A type annotation is necessary.

### ISSUE THREAD

**Issue by marinsokol5** [reduxjs/redux-toolkit#5014]
Hey folks, 

Opening as a duplicate of https://github.com/reduxjs/redux-toolkit/issues/1806 since I can't comment on that thread. 

It's indeed a small type issue, and I am opening it just because of the high bar for your existing types. If this was another library, I would not even bother.

But effectively, I agree with https://github.com/reduxjs/redux-toolkit/issues/1806#issuecomment-1925437633, and v2.2.7 does not solve the problem. 

[Link to TS playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZQDbDJpwC+cAZlBCHAOQAC6AJgK4AeAVgM4D0MEEPAGtgMWgChQkWHBgBPMMSQAFDHLwQMTAILIYwCADtSFKjQbN23PgOGiJkw9ijkMROAGEILJ2ig4YLCVxODgANww8FjQALjhDFhAAIz9xEnFxZCMueGBDUWBIgKC4AF5EcMjouIAGEy4sYC5yYDQuT29ff0DsOAx2rx9nYuwMtDZpeCzDHJRO4YJ3ctRMbHxCNAAKBBD4jBBYuiyhv1oAGl28gqKetAvQyyIoLjid0NC8lYOnTZyggEpELt3nA-tgAHQRKJoADUMOBpHu7yYaC+aB+YLQgLeINBt0hVTQAFoiQiSEiPoY0U4AEJybQgea-W5nPp6AyGOKqdSaHTsowAHgSyT8AD5sQjQpiCdC4DDym59EZwWA1BotGSkeS0v8gA)

Copying the example code from https://redux-toolkit.js.org/api/createslice:
```ts
import { createSlice } from '@reduxjs/toolkit'
import type { PayloadAction } from '@reduxjs/toolkit'

interface CounterState {
  value: number
}

const initialState = { value: 0 } satisfies CounterState as CounterState

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    increment(state) {
      state.value++
    },
    decrement(state) {
      state.value--
    },
    incrementByAmount(state, action: PayloadAction<number>) {
      state.value += action.payload
    },
  },
})
```

into https://www.typescriptlang.org/play, transpiles into

```ts
import type { PayloadAction } from '@reduxjs/toolkit';
interface CounterState {
    value: number;
}
export declare const counterSlice: import("@reduxjs/toolkit").Slice<CounterState, {
    increment(state: import("immer").WritableDraft<CounterState>): void;
    decrement(state: import("immer").WritableDraft<CounterState>): void;
    incrementByAmount(state: import("immer").WritableDraft<CounterState>, action: PayloadAction<number>): void;
}, "counter", "counter", import("@reduxjs/toolkit").SliceSelectors<CounterState>>;
export {};
```

That is quite problematic, because the `WritableDraft` will depend on root-level immer version, not the one used by RTK. That works only if those are the same, else folks would get such (rightful) compilation errors from above.
This happens because `WritableDraft` is inferred from [`Draft`](https://github.com/immerjs/immer/blob/main/src/types/types-external.ts#L47) but not exported.

If it was this would get transpiled to much nicer
```ts
import("@reduxjs/toolkit").WritableDraft
```
which would then lead to the immer attached to RTK, which may be the root one, and may be the "node_modules/RTK/node_modules/immer".

**Comment by puehringer** [comment]
Could it be that this issue was reintroduced in 11.1.3 with https://github.com/immerjs/immer/pull/1197 with the new `WritableNonArrayDraft` type? I.e. `WritableDraft` depends on `WritableNonArrayDraft`, which is neither exported from immer nor redux-toolkit, leading to the following error: `Exported variable 'counterSlice' has or is using name 'WritableNonArrayDraft' from external module "./node_modules/@reduxjs/toolkit/node_modules/immer/dist/immer" but cannot be named.`

I'll have to investigate further to create a reproducible example, because it seems to depend on the state type as well.

**Comment by SimpleCreations** [comment]
Why is this closed? This is still an issue. Popped up after upgrading to 2.11 from 2.10.

**Comment by markerikson** [comment]
@SimpleCreations it was closed because it _was_ fixed at the time.  It's possible that the recent Immer 11 changes caused the equivalent problem to pop up again.  If you're seeing an error like this, please provide a repro that demonstrates this happening.

**Comment by CharlieBreval12** [comment]
I confirm I got the issue : 
```
TS4023: Exported variable managerGroupFiltersSlice has or is using name WritableNonArrayDraft from external module
'.../node_modules/.pnpm/immer@11.1.3/node_modules/immer/dist/immer'
but cannot be named.
```
**@reduxjs/toolkit : 2.11.2**


EDIT : I found how to fix it and what was wrong.
I was doing an export of the slice like : 
```
export const managerFormSlice = createSlice({
```

And in some cases (not sure why), I had the error.
You can avoid having this issue by not exporting your slice.
