### ISSUE TITLE
Can't create action with no payload

### ISSUE THREAD

**Issue by eliana-fairstreet** [reduxjs/redux-toolkit#3373]
I'm creating a very simple reducer that manages a string field:

```typescript
import { createSlice, PayloadAction, Slice } from '@reduxjs/toolkit';

const initialState = 'LastUpdated';

const sortBy = createSlice({
    name: `sortBy`,
    initialState,
    reducers: {
      set: (_state: string, action: PayloadAction<string>) => (action.payload),
      clear: () => initialState,
    }
});
```

Typescript is fine with this declaration, but if I try to call `sortBy.actions.clear()`, I get a typescript compilation error complaining that I'm missing a required argument (the action payload). I've tried a number of fixes, including defining `clear` as follows:
```typescript
clear: (_state: string, _action: PayloadAction<null>) => initialState
```

Nothing I try seems to work. Is there a way to do this that Typescript accepts?

I'm working with typescript 4.5.5 and redux-toolkit 1.9.3.

**Comment by markerikson** [comment]
You shouldn't need to declare `_state: string`.  RTK and TS should infer the type already.  However, you should also probably ensure that `initialState` is typed as a `string`, otherwise TS might infer the type too tightly.

**Comment by phryneas** [comment]
Do you have `strict: true` in your `tsconfig.json`? If so, what exact error (with error number) are you getting?

**Comment by eliana-fairstreet** [comment]
We do not currently have strict mode turned on. The error we're receiving is here:
![Screenshot 2023-04-17 at 3 49 09 PM](https://user-images.githubusercontent.com/126526695/232626938-7d81c0a9-46df-4f22-82d9-c6d85a1bec6b.png)

**Comment by markerikson** [comment]
@eliana-fairstreet : we specifically want users to have `strict: true` when using RTK. Having that turned off _does_ change the behavior of some types in ways that break them, and we can't test or offer support for how they behave in that situation.  Please try turning on `strict: true` and see what happens.

**Comment by phryneas** [comment]
In your case, this error might occur because `strictNullChecks` is off, which will confuse our internal types horribly. `null | string` and `string`, `void | string` and `undefined | string` are the same type in that environment - and we use `void` to determine if you added a parameter or not.

**Comment by eliana-fairstreet** [comment]
Thank you both for the context. I will follow up on my team to get us switched over to strict mode. Given that may take a while and that it's likely the cause of our problem, I can close this issue for now.
