### ISSUE TITLE
@rtk-query/codegen-openapi documentation is misleading in regard to endpointOverrides -> parameterFilter

### ISSUE THREAD

**Issue by hadrian625** [reduxjs/redux-toolkit#4612]
In the docs for endpointOverrides https://redux-toolkit.js.org/rtk-query/usage/code-generation#endpoint-overrides it is mentioned that a parameterFilter exists which would allow filtering out paramters not desired from the openapi specs. But no such field exists.
Is this a mistake in the documentation or the documentation is showing something that is in development right now?

I am using @rtk-query/codegen-openapi 1.2.0
I type definition for EndpointOverrides there is only "pattern" and "type"
export interface EndpointOverrides {
    pattern: EndpointMatcher;
    type: 'mutation' | 'query';
}

**Comment by phryneas** [comment]
I think this is something that was already merged, but not released yet. Could you try the latest alpha release?

**Comment by anotheri** [comment]
I can confirm it works in the latest version (2.2.0) as expected
